#!/usr/bin/env node
/**
 * build-sea.mjs — Build a Node.js SEA (Single Executable Application) for blindfold
 *
 * Steps:
 * 1. Run tsc to produce typed dist/
 * 2. Bundle dist/cli/index.js with esbuild into dist/sea-bundle.cjs (CJS, fully bundled)
 * 3. Generate sea-config.json pointing to dist/sea-bundle.cjs
 * 4. Run `node --experimental-sea-config` to produce the blob
 * 5. Copy the node binary and inject the blob with postject
 * 6. Set executable bit
 * 7. Clean up blob and sea-config.json (not needed in published tarball)
 *
 * Node.js SEA requires a CommonJS entry point. The ESM dist/cli/index.js cannot
 * be used directly — esbuild bundles everything into a single CJS file, resolving
 * all dynamic imports (which use statically-known string literals) at bundle time.
 */

import { build } from 'esbuild';
import { execSync } from 'node:child_process';
import { copyFileSync, chmodSync, writeFileSync, existsSync, mkdirSync, rmSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const distDir = join(root, 'dist');

mkdirSync(distDir, { recursive: true });

// ── Step 1: compile TypeScript ────────────────────────────────────────────────
console.log('[1/5] Compiling TypeScript...');
execSync('npx tsc', { cwd: root, stdio: 'inherit' });

// ── Step 2: bundle with esbuild into CJS ─────────────────────────────────────
console.log('[2/5] Bundling with esbuild (CJS)...');

const bundlePath = join(distDir, 'sea-bundle.cjs');

// esbuild cannot emit top-level await in CJS format (CJS is synchronous by
// definition). The CLI entry uses top-level await extensively. The fix: write a
// thin CJS-compatible wrapper that delegates to the compiled cli/index.js entry
// via an async IIFE. esbuild bundles this wrapper (CJS) and inlines all imports.
// The dynamic import('./secret.js') etc. use statically-known paths — esbuild
// resolves them at bundle time.
// Place wrapper in dist/cli/ so relative requires resolve to compiled modules there
const wrapperPath = join(distDir, 'cli', '_sea-entry.cjs');
writeFileSync(wrapperPath, [
  '"use strict";',
  '// SEA entry wrapper — generated by build-sea.mjs',
  '// Wraps the ESM CLI entry in an async IIFE so esbuild can emit CJS.',
  '(async () => {',
  "  const { initBlindfold } = require('../config.js'); // dist/config.js",
  "  const args = process.argv.slice(2);",
  "  const command = args[0];",
  "  if (command === '--version' || command === '-v') {",
  "    const pkg = require('../../package.json');",
  "    console.log('blindfold ' + pkg.version);",
  '    process.exit(0);',
  '  }',
  "  if (command === '--help' || command === '-h') {",
  "    console.error('Usage: blindfold [command]');",
  "    console.error('');",
  "    console.error('Commands:');",
  "    console.error('  (none)    Start MCP server (stdio)');",
  "    console.error('  secret    Manage secrets (--set, --list, --update, --delete)');",
  "    console.error('  auth      Out-of-band authentication (--confirm)');",
  "    console.error('  install   Register blindfold as an MCP server');",
  "    console.error('  serve     Start MCP server (stdio) — alias for no command');",
  "    console.error('');",
  "    console.error('Options:');",
  "    console.error('  --version  Show version');",
  "    console.error('  --help     Show this help');",
  '    process.exit(0);',
  '  }',
  '  initBlindfold();',
  "  if (command === 'secret') {",
  "    const { runSecret } = require('./secret.js'); // dist/cli/secret.js",
  '    await runSecret(args.slice(1));',
  "  } else if (command === 'auth') {",
  "    const { runAuth } = require('./auth.js'); // dist/cli/auth.js",
  '    await runAuth(args.slice(1));',
  "  } else if (command === 'install') {",
  "    const { runInstall } = require('./install.js'); // dist/cli/install.js",
  '    await runInstall(args.slice(1));',
  "  } else if (command === 'serve' || !command) {",
  "    const { startMcpServer } = require('../mcp/server.js');",
  '    await startMcpServer();',
  '  } else {',
  "    console.error('Unknown command: ' + command);",
  '    console.error(\'Run "blindfold --help" for usage.\');',
  '    process.exit(1);',
  '  }',
  '})();',
].join('\n'));

await build({
  entryPoints: [wrapperPath],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'cjs',
  outfile: bundlePath,
  sourcemap: false,
  minify: false,
  // Bundle everything — no externals — so the SEA blob is self-contained.
  external: [],
  banner: {
    js: [
      '// Node.js SEA bundle — generated by build-sea.mjs',
      // Shim import.meta.url for any modules that use it (e.g. auth-socket.ts)
      'var __importMetaUrl = typeof __filename !== "undefined" ? require("url").pathToFileURL(__filename).href : "";',
    ].join('\n'),
  },
  define: {
    'import.meta.url': '__importMetaUrl',
  },
});

// Clean up the temp wrapper
try { unlinkSync(wrapperPath); } catch { /* ignore */ }

console.log(`  Bundle written: ${bundlePath}`);

// ── Step 3: generate sea-config.json ─────────────────────────────────────────
console.log('[3/5] Generating sea-config.json...');

const seaConfigPath = join(distDir, 'sea-config.json');
const blobPath = join(distDir, 'sea-prep.blob');

const seaConfig = {
  main: bundlePath,
  output: blobPath,
  disableExperimentalSEAWarning: true,
  useCodeCache: false,
};

writeFileSync(seaConfigPath, JSON.stringify(seaConfig, null, 2));
console.log(`  Written: ${seaConfigPath}`);

// ── Step 4: generate the blob ─────────────────────────────────────────────────
console.log('[4/5] Generating SEA blob...');
execSync(`node --experimental-sea-config "${seaConfigPath}"`, {
  cwd: root,
  stdio: 'inherit',
});

if (!existsSync(blobPath)) {
  console.error('Error: SEA blob was not generated.');
  process.exit(1);
}

// ── Step 5: copy node + inject blob ──────────────────────────────────────────
const platform = process.platform;
const arch = process.arch;
const platformMap = { win32: 'win', darwin: 'darwin', linux: 'linux' };
const ext = platform === 'win32' ? '.exe' : '';
const binaryName = `blindfold-${platformMap[platform] || platform}-${arch}${ext}`;
const outputBinary = join(root, binaryName);

console.log(`[5/5] Building binary: ${binaryName}`);

// Copy node
copyFileSync(process.execPath, outputBinary);

// macOS: strip existing codesign before injection
if (platform === 'darwin') {
  console.log('  Stripping macOS codesign...');
  execSync(`codesign --remove-signature "${outputBinary}"`, { stdio: 'inherit' });
}

// Inject blob with postject (use local node_modules/.bin/postject if available)
const postjectBin = existsSync(join(root, 'node_modules', '.bin', 'postject'))
  ? join(root, 'node_modules', '.bin', 'postject')
  : (platform === 'win32' ? 'npx.cmd' : 'npx') + ' postject';

const postjectArgs = [
  `"${outputBinary}"`,
  'NODE_SEA_BLOB',
  `"${blobPath}"`,
  '--sentinel-fuse', 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
];

if (platform === 'darwin') {
  postjectArgs.push('--macho-segment-name', 'NODE_SEA');
}

try {
  if (existsSync(join(root, 'node_modules', '.bin', 'postject'))) {
    // Use local binary directly (no npx needed)
    const localPostject = join(root, 'node_modules', '.bin', 'postject');
    execSync(
      `"${localPostject}" ${postjectArgs.join(' ')}`,
      { cwd: root, stdio: 'inherit', shell: platform === 'win32' ? true : undefined }
    );
  } else {
    const npxCmd = platform === 'win32' ? 'npx.cmd' : 'npx';
    execSync(
      `${npxCmd} postject ${postjectArgs.join(' ')}`,
      { cwd: root, stdio: 'inherit', shell: platform === 'win32' ? true : undefined }
    );
  }
} catch (err) {
  if (err.message?.includes('postject') || String(err).includes('postject')) {
    console.error('\nError: postject not found. It should be installed as a devDependency.');
    console.error('  Run: npm install');
    process.exit(1);
  }
  throw err;
}

// macOS: re-sign with ad-hoc signature
if (platform === 'darwin') {
  console.log('  Re-signing macOS binary with ad-hoc signature...');
  execSync(`codesign --sign - "${outputBinary}"`, { stdio: 'inherit' });
}

// Set executable bit (non-Windows)
if (platform !== 'win32') {
  chmodSync(outputBinary, 0o755);
}

// ── Cleanup: remove SEA build artifacts so they don't end up in published tarball
console.log('  Cleaning up SEA build artifacts...');
try {
  rmSync(blobPath, { force: true });
  rmSync(seaConfigPath, { force: true });
  rmSync(bundlePath, { force: true });
} catch {
  // non-fatal
}

console.log(`\nSEA binary ready: ${binaryName}`);
